name: Deploy API Server to Dev EB

on:
  push:
    tags:
      - '*'


jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate deployment package
        run: zip -r server.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: application
          environment_name: Application-env
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.ref_name }}
          deployment_package: server.zip
          wait_for_environment_recovery: 300
